name: Package testing
run-name: Testing ${{ github.sha }} commit
on: [push]

jobs:
  test-package:
    strategy:
      matrix:
        version: ["3.8.1", "3.9.2", "3.10", "3.11", "3.12"]
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Install Django
        run: |
          if [[ "${{ matrix.version }}" == "3.8.1" ]]; then
            echo "Installing Django 4.2 for Python ${{ matrix.version }}"
            pip install django==4.2
          elif [[ "${{ matrix.version }}" == "3.9.2" ]]; then
            echo "Installing Django 4.2 for Python ${{ matrix.version }}"
            pip install django==4.2
          elif [[ "${{ matrix.version }}" == "3.10" ]]; then
            echo "Installing Django 5.0 for Python ${{ matrix.version }}"
            pip install django==5.0
          elif [[ "${{ matrix.version }}" == "3.11" ]]; then
            echo "Installing Django 5.0 for Python ${{ matrix.version }}"
            pip install django==5.0
          elif [[ "${{ matrix.version }}" == "3.11" ]]; then
            echo "Installing Django 5.0 for Python ${{ matrix.version }}"
            pip install django==5.0
          fi
      - name: Set up Poetry
        run: pip install poetry && poetry config virtualenvs.create false && poetry install
      - name: Run tests
        run: CI=true script/test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.version }}
          path: htmlcov/
          retention-days: 30
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
