name: GitHub Actions Demo
run-name: ${{ github.action }} is testing package
on: [push]

jobs:
  test-package:
    strategy:
      matrix:
        version: ["3.8.1", "3.9.2", "3.10", "3.11", "3.12"]
        include:
          - version: "3.8.1"
            django: "1.9"
            os: "ubuntu-20.04"
          - version: "3.9.2"
            django: "4.2"
            os: "ubuntu-20.04"
    runs-on: ${{ env.OS }}
    steps:
      - name: Set OS variable
        run: echo "OS=${{ matrix.os || 'ubuntu-latest' }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: pip install poetry
      - run: poetry install
      - run: CI=true script/test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
