name: GitHub Actions Demo
run-name: ${{ github.action }} is testing package
on: [push]

jobs:
  test-package:
    strategy:
      matrix:
        version: ["3.8.1", "3.9.2", "3.10", "3.11", "3.12"]
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Set up Poetry
        run: pip install poetry && poetry install
      - name: Run tests
        run: CI=true script/test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.version }}
          path: htmlcov/
          retention-days: 30
